@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Component.puml
LAYOUT_WITH_LEGEND()
Person(user, "Person", "A user of the calendar system")
rectangle "Allows users to view events" {
    Component(calendar, "Mobile App Android", "Show all events")
    Component_Ext(api_google_events, "API Google", "Get all events from Google Calendar")
}
Rel(calendar, api_google_events, "Uses")
Rel(user, calendar, "Uses")
@enduml
